Upgrade Gradle to avoid dex merge error (#1)
Bug in gradle 6.9 causing following error:

com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
...
> Task :app:mergeExtDexRelease FAILED
...
Type androidx.appcompat.app.ActionBar$DisplayOptions is defined multiple times

Apparently Expo's Gradle has been updated to 7.3.3 in the meantime, but not yet released:

https://github.com/expo/expo/commit/d566f199bdb03f738c8a785283e847b6a00ec37a